version: '3.8'

services:
  veeam-insight:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veeam-insight-dashboard
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
      - "${WS_PORT:-3002}:${WS_PORT:-3002}"
    environment:
      # Application Configuration
      - NODE_ENV=production
      - PORT=${PORT:-3001}
      - WS_PORT=${WS_PORT:-3002}
      
      # Veeam Configuration
      - VEEAM_SERVER=${VEEAM_SERVER}
      - VEEAM_USERNAME=${VEEAM_USERNAME}
      - VEEAM_PASSWORD=${VEEAM_PASSWORD}
      - VEEAM_PORT=${VEEAM_PORT:-9419}
      
      # Security
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
      
      # Cache Configuration
      - CACHE_TTL=${CACHE_TTL:-300}
      
      # Rate Limiting
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - LOGIN_RATE_LIMIT_WINDOW=${LOGIN_RATE_LIMIT_WINDOW:-900000}
      - LOGIN_RATE_LIMIT_MAX=${LOGIN_RATE_LIMIT_MAX:-5}
      
      # Monitoring
      - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL:-30000}
      - ALERT_CHECK_INTERVAL=${ALERT_CHECK_INTERVAL:-60000}
      
      # WhatsApp Integration (Optional)
      - WHATSAPP_API_URL=${WHATSAPP_API_URL}
      - WHATSAPP_API_TOKEN=${WHATSAPP_API_TOKEN}
      - WHATSAPP_PHONE_NUMBER=${WHATSAPP_PHONE_NUMBER}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-/app/logs/app.log}
    volumes:
      - ./logs:/app/logs
      - ./server/tokens.json:/app/tokens.json
      # Share frontend build files with nginx
      - frontend-dist:/app/public
    networks:
      - veeam-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${PORT:-3001}/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: veeam-insight-nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-9007}:80"
      - "${HTTPS_PORT:-9008}:443"
    volumes:
      # Use HTTP-only config template (change to nginx.conf.template for HTTPS)
      - ./nginx-http.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./ssl:/etc/nginx/ssl:ro
      # Mount frontend build files from the main container
      - frontend-dist:/usr/share/nginx/html:ro
    environment:
      - ENABLE_SSL=${ENABLE_SSL:-false}
      - BACKEND_HOST=${BACKEND_HOST:-veeam-insight}
      - BACKEND_PORT=${BACKEND_PORT:-3003}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST:-veeam-insight}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT:-3002}
    entrypoint: ["/docker-entrypoint.sh"]
    networks:
      - veeam-network
    depends_on:
      - veeam-insight
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  frontend-dist:
    driver: local

networks:
  veeam-network:
    driver: bridge